import pyautogui

# pyautogui.hotkey('win','m')
# pyautogui.rightClick(300,300)
# pyautogui.press('Down')
# pyautogui.press('Down')
# pyautogui.press('Down')
# pyautogui.press('enter')
# pyautogui.hotkey('win','shift','m')

# pyautogui.hotkey('fn','Right')
# pyautogui.hotkey('fn','Right')
# pyautogui.hotkey('fn','Right')
# pyautogui.hotkey('fn','Right')
# pyautogui.hotkey('fn','Right')

# time.sleep(2)
# pyautogui.rightClick(300,300)
# pyautogui.press('Down')
# pyautogui.press('Down')
# pyautogui.press('Down')
# pyautogui.press('Down')
# pyautogui.press('enter')

# pyautogui.press('win')
# pyautogui.typewrite('system',1)
# pyautogui.press('enter')
# time.sleep(2)
# pyautogui.leftClick(x=515,y=341)
# pyautogui.hotkey('ctrl','a')
# pyautogui.hotkey('ctrl','c')
# speak(clipboard.paste())
# '''
# query=input(':')
# a = query.replace('calculate','')
# pyautogui.hotkey('win','m')
# time.sleep(1)
# pyautogui.press('win')
# time.sleep(1)
# pyautogui.write('calcu',0.2)
# pyautogui.press('enter')
# time.sleep(5)
# #pyautogui.leftClick(x=425,y=319)

# #time.sleep(2)
# pyautogui.write(a,0.5)
# pyautogui.press('enter')
# pyautogui.click(x=352,y=149,clicks=1,interval=0,button='left')
# pyautogui.hotkey('ctrl','a')
# pyautogui.hotkey('ctrl','c')
# speak(f'{a} equals'+clipboard.paste())
# print(pyautogui.KEYBOARD_KEYS)
# pyautogui.sleep(2)
pyautogui.hotkey('win','m')
